language: java

sudo: false
dist: trusty

cache:
  directories:
  - $HOME/.m2
  - $HOME/ltsmin

before_cache:
  # do not cache our local archives
  - rm -rf $HOME/.m2/repository/net/automatalib/
  - rm -rf $HOME/.m2/repository/de/learnlib/

branches:
  only:
  - master
  - develop
  - release

before_install:
    # set Travis environment variables "AUTOMATALIB_FORK" and "AUTOMATALIB_BRANCH" to build custom AutomataLib versions.
    # Defaults are "LearnLib" and the current/targeted LearnLib branch ($TRAVIS_BRANCH, relies on the same naming
    # conventions between AutomataLib and LearnLib branches).
  - git clone -b ${AUTOMATALIB_BRANCH:-$TRAVIS_BRANCH} --single-branch https://github.com/${AUTOMATALIB_FORK:-LearnLib}/automatalib.git /tmp/automatalib-develop
  - pushd /tmp/automatalib-develop
  - mvn install -DskipTests
  - popd

install:
  # install LTSmin
  - build-tools/install-ltsmin.sh
  - PATH="$PATH:$HOME/ltsmin/v3.0.0/bin"

script:
  - mvn install -B -Pintegration-tests,code-analysis,bundles

jobs:
  fast_finish: true
  allow_failures:
    - jdk: openjdk9
      env: MAVEN_OPTS="$MAVEN_OPTS -Dmaven.compiler.source=9 -Dmaven.compiler.target=9"
    - jdk: openjdk10
      env: MAVEN_OPTS="$MAVEN_OPTS -Dmaven.compiler.source=10 -Dmaven.compiler.target=10"
  include:
    - jdk: openjdk8
    - jdk: oraclejdk8
    - jdk: openjdk9
    - jdk: oraclejdk9
    - jdk: openjdk10
    - jdk: oraclejdk10
    - jdk: openjdk9
      env: MAVEN_OPTS="$MAVEN_OPTS -Dmaven.compiler.source=9 -Dmaven.compiler.target=9"
    - jdk: openjdk10
      env: MAVEN_OPTS="$MAVEN_OPTS -Dmaven.compiler.source=10 -Dmaven.compiler.target=10"
    - stage: coverage
      jdk: openjdk8 # use openjdk8 build
      script:
        - mvn install -B -Pintegration-tests,code-coverage
        - mvn coveralls:report
    - stage: deploy
      jdk: openjdk8 # use openjdk build
      before_install: true # skip building AutomataLib, because we actually want to link against the deployed artifacts.
      install: true # skip the normal build
      script: skip # skip the normal build
      deploy:
        # define deployment in deploy phase, which is skipped for pull-requests
        provider: script
        script: mvn --settings build-tools/travis-settings.xml -DskipTests=true deploy
        on:
          branch: develop # only auto deploy snapshots
