language: java

sudo: false
dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
  - $HOME/.m2

before_cache:
  # do not cache our local archives
  - rm -rf $HOME/.m2/repository/net/automatalib/
  - rm -rf $HOME/.m2/repository/de/learnlib/

branches:
  only:
  - master
  - develop

before_install:
    # set Travis environment variables "AUTOMATALIB_FORK" and "AUTOMATALIB_BRANCH" to build custom AutomataLib versions.
    # Defaults are "LearnLib" and "develop".
  - git clone -b ${AUTOMATALIB_BRANCH:-develop} --single-branch https://github.com/${AUTOMATALIB_FORK:-LearnLib}/automatalib.git /tmp/automatalib-develop
  - pushd /tmp/automatalib-develop
  - mvn install -DskipTests
  - popd

install: true # skip mvn install, because we essentially run the same command in the script routine

script:
  - mvn install -B -Pintegration-tests,code-analysis,code-coverage,bundles
  - mvn coveralls:report

jobs:
  include:
    - stage: deploy
      jdk: openjdk8 # use openjdk build
      install: true # skip the normal build
      script: skip # skip the normal build
      deploy:
        # define deployment in deploy phase, which is skipped for pull-requests
        provider: script
        script: mvn --settings build-tools/travis-settings.xml -DskipTests=true deploy
        on:
          branch: develop # only auto deploy snapshots
